# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'fg-myu-dev-pipeline-connection'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './find-tf-expiring-resources.sh'
    arguments: '1y'

container: